[workspace]
members = [
    # main crates, published on crates.io
    "capnp",
    "capnpc",
    "capnp-futures",
    "capnp-rpc",
    "capnp-conv",

    # testing and examples
    "async-byte-channel",
    "benchmark",
    "capnpc/test",
    "capnp-futures/test",
    "capnp-rpc/examples/hello-world",
    "capnp-rpc/examples/calculator",
    "capnp-rpc/examples/pubsub",
    "capnp-rpc/test",
    "example/addressbook",
    "example/addressbook_send",
]
default-members = [
    "capnp",
    "capnpc",
    "capnp-conv",
]
